// Sample product data for women's clothing collection
export const sampleProducts = [
  {
    name: "Premium Cotton Kurti",
    slug: "premium-cotton-kurti",
    description: "Comfortable everyday cotton kurti with intricate embroidery",
    longDescription:
      "Perfect for casual wear or festive occasions, this premium cotton kurti features traditional hand embroidery with a modern silhouette. Breathable fabric ideal for warm weather.",
    price: 2499,
    images: ["/colorful-cotton-kurti.png", "/colorful-cotton-kurti.png"],
    category: "Kurtis",
    subcategory: "Casual",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Navy Blue", "Maroon", "Cream"],
    material: "100% Cotton",
    care: "Hand wash in cold water",
    inStock: true,
    stockCount: 45,
    rating: 4.5,
    reviews: [],
    featured: true,
  },
  {
    name: "Embroidered Silk Kurti",
    slug: "embroidered-silk-kurti",
    description: "Elegant silk kurti with traditional embroidery work",
    longDescription:
      "Crafted with premium silk fabric, this kurti features intricate mirror work embroidery. Perfect for festivals and celebrations with a timeless appeal.",
    price: 3999,
    images: ["/colorful-cotton-kurti.png", "/colorful-cotton-kurti.png"],
    category: "Kurtis",
    subcategory: "Festive",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal", "Emerald", "Wine"],
    material: "Pure Silk",
    care: "Dry clean only",
    inStock: true,
    stockCount: 30,
    rating: 4.7,
    reviews: [],
    featured: true,
  },
  {
    name: "Classic Silk Saree",
    slug: "classic-silk-saree",
    description: "Luxurious silk saree with traditional weaving patterns",
    longDescription:
      "Draped in elegance, this silk saree showcases traditional weaving patterns with modern appeal. Perfect for weddings, celebrations, and formal occasions.",
    price: 8999,
    images: ["/elegant-woman-in-silk-saree.png", "/elegant-woman-in-silk-saree.png"],
    category: "Sarees",
    subcategory: "Silk",
    sizes: ["One Size"],
    colors: ["Emerald Green", "Burgundy", "Gold"],
    material: "Mulberry Silk",
    care: "Dry clean only",
    inStock: true,
    stockCount: 20,
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    name: "Cotton Saree",
    slug: "cotton-saree",
    description: "Breathable cotton saree for everyday elegance",
    longDescription:
      "A comfortable yet elegant cotton saree suitable for daily wear. The traditional weave with subtle patterns makes it versatile for both casual and semi-formal occasions.",
    price: 2999,
    images: ["/elegant-woman-in-silk-saree.png", "/elegant-woman-in-silk-saree.png"],
    category: "Sarees",
    subcategory: "Cotton",
    sizes: ["One Size"],
    colors: ["White", "Indigo", "Peach"],
    material: "100% Cotton",
    care: "Machine wash on gentle cycle",
    inStock: true,
    stockCount: 25,
    rating: 4.3,
    reviews: [],
    featured: false,
  },
  {
    name: "Elegant Palazzo Suit",
    slug: "elegant-palazzo-suit",
    description: "Contemporary palazzo suit with modern designs",
    longDescription:
      "A perfect blend of tradition and contemporary style, this palazzo suit features a fitted kurti with flowy palazzo pants. Ideal for casual gatherings and festive celebrations.",
    price: 3499,
    images: ["/classic-navy-suit.png", "/classic-navy-suit.png"],
    category: "Suits",
    subcategory: "Palazzo",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Navy", "Peach"],
    material: "Cotton Blend",
    care: "Machine wash in cold water",
    inStock: true,
    stockCount: 35,
    rating: 4.3,
    reviews: [],
    featured: true,
  },
  {
    name: "Printed Suit Set",
    slug: "printed-suit-set",
    description: "Trendy printed suit with comfortable fit",
    longDescription:
      "Modern printed kurti paired with comfortable churidar. Perfect for everyday wear with a traditional touch. Available in various prints and colors.",
    price: 2799,
    images: ["/classic-navy-suit.png", "/classic-navy-suit.png"],
    category: "Suits",
    subcategory: "Printed",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Multicolor", "Navy Print", "Green Print"],
    material: "Cotton Blend",
    care: "Machine wash on gentle cycle",
    inStock: true,
    stockCount: 40,
    rating: 4.4,
    reviews: [],
    featured: false,
  },
]
